# action.yml
name: 'Test results uploader to Test-hub.io'
description: 'Upload test results to Test-hub.io'
inputs:

  test-result-pattern:
    description: 'Test results file pattern. A glob pattern. Could be path with wildcards like /target/**/TestResults*.xml'
    required: true
    default: '**/TestResults*.xml'
  
  test-coverage-pattern:
    description: 'Test coverage file pattern. A glob pattern. Could be path with wildcards like /target/**/jacoco.xml'
    required: false
    default: '/target/**/jacoco.xml'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-result-pattern }}